### PR TITLE
Refactor seed prompt loading: replace text file with Python class for easier maintenance

### PR DESCRIPTION
**Pull request by AlrikOlson**
This is a follow-up and improvement to my previous PR #760 

### Background

The initial implementation involved loading a seed prompt from a text file (prompt.txt). While this worked, it made the process of editing the seed prompt cumbersome and less efficient. To improve this process, this pull request refactors the method by which the seed prompt is loaded and generated, transitioning from a text file to a Python class. This will simplify editing the seed prompt and streamline the overall workflow.

### Changes

1. Removed prompt.txt from the project.
2. Created a new Python class `PromptGenerator` in a separate file (`promptgenerator.py`), which contains the necessary methods to build the seed prompt.
3. Refactored the main application code to import and utilize the `PromptGenerator` class instead of loading the prompt from the text file.

### Documentation

Code is fully commented.

### Test Plan

Unit tests have been written for the `PromptGenerator` class. I've also tested this functionality with several basic prompts, including the base `ai_settings.yml`

### PR Quality Checklist
- [x] My pull request is atomic and focuses on a single change.
- [x] I have thouroughly tested my changes with multiple different prompts.
- [x] I have considered potential risks and mitigations for my changes.
- [x] I have documented my changes clearly and comprehensively.
- [x] I have not snuck in any "extra" small tweaks changes

### CODE REVIEW

**Review by dragonboy144 — APPROVED** [review]

**Review by nponeccop — APPROVED** [review]

**Comment by AlrikOlson** [comment]
Thought the `AttributeError: 'Config' object has no attribute 'debug'` issue was caused by my changes, but it appears to be a current defect in `master`

**Comment by claytondukes** [comment]
> Thought the `AttributeError: 'Config' object has no attribute 'debug'` issue was caused by my changes, but it appears to be a current defect in `master`

There's a PR fix for it: https://github.com/Torantulino/Auto-GPT/pull/839#issue-1662956097

**Comment by AlrikOlson** [comment]
> > Thought the `AttributeError: 'Config' object has no attribute 'debug'` issue was caused by my changes, but it appears to be a current defect in `master`
> 
> There's a PR fix for it: [#839 (comment)](https://github.com/Torantulino/Auto-GPT/pull/839#issue-1662956097)

There appears to be several PRs trying to fix the same issue, yeah

**Comment by nponeccop** [comment]
Is there an issue for this problem?

**Review by nponeccop — APPROVED** [review]

**Comment by nponeccop** [comment]
@AlrikOlson There are conflicts again

**Review by nponeccop — APPROVED** [review]

**Comment by AlrikOlson** [comment]
> @AlrikOlson There are conflicts again

Fixed merge conflict, made sure to add the new `execute_shell` command to `prompt.py`

**Review by nponeccop — DISMISSED** [review]

**Comment by nponeccop** [comment]
@AlrikOlson There are conflicts again

**Comment by AlrikOlson** [comment]
@nponeccop resolved

**Comment by richbeales** [comment]
Conflicting files
scripts/data/prompt.txt 

scripts/prompt.py:3:1: E302 expected 2 blank lines, found 1
scripts/prompt.py:6:1: W293 blank line contains whitespace
scripts/prompt.py:61:1: W293 blank line contains whitespace
tests/promptgenerator_tests.py:11:1: E302 expected 2 blank lines, found 1
tests/promptgenerator_tests.py:84:1: W293 blank line contains whitespace
tests/promptgenerator_tests.py:98:1: E305 expected 2 blank lines after class or function definition, found 1

**Comment by AlrikOlson** [comment]
> Conflicting files scripts/data/prompt.txt
> 
> scripts/prompt.py:3:1: E302 expected 2 blank lines, found 1 scripts/prompt.py:6:1: W293 blank line contains whitespace scripts/prompt.py:61:1: W293 blank line contains whitespace tests/promptgenerator_tests.py:11:1: E302 expected 2 blank lines, found 1 tests/promptgenerator_tests.py:84:1: W293 blank line contains whitespace tests/promptgenerator_tests.py:98:1: E305 expected 2 blank lines after class or function definition, found 1

resolved

**Review by nponeccop — APPROVED** [review]

**Comment by sameerpanjwani** [comment]
Have these commands been intentionally removed, they no longer required?

2. Memory Add: "memory_add", args: "string": "<string>"
3. Memory Delete: "memory_del", args: "key": "<key>"
4. Memory Overwrite: "memory_ovr", args: "key": "<key>", "string": "<string>"

**Comment by AlrikOlson** [comment]
> Have these commands been intentionally removed, they no longer required?
> 
> 2. Memory Add: "memory_add", args: "string": "<string>"
> 3. Memory Delete: "memory_del", args: "key": "<key>"
> 4. Memory Overwrite: "memory_ovr", args: "key": "<key>", "string": "<string>"

This PR did not change add/remove/modify any commands.

Memory commands were removed in a separate change unrelated to this one.

**Pull request merged**
