### PR TITLE
Use yaml prompt non-interactively

### PR DESCRIPTION
**Pull request by josephcmiller2**
### Background
Currently, user input is required before a goal is processed. Adding the argument --use-yaml-prompt allows full continuous mode without user input so that testing can be automated and a series of prompts can be executed by setting up a series of commands. Full continuous mode can be limited by the newly added "--continuous-limit" to prevent it from running forever and mucking up your API accounts.

### Changes
- Add argument '--use-yaml-prompt' to automatically use the prompt in the yaml file without requiring user input
- Add an argument to construct_prompt(), non_interactive=False, so the non-interactive behavior is optional and not the default

### Documentation
- In-code comments
- Command-line argument includes help which describes what it does.

### Test Plan
- Test without --use-yaml-prompt, behavior is the same as before code changes
- Test with --use-yaml-prompt, script uses ai_settings.yaml and does not prompt the user to confirm

### PR Quality Checklist
- [X] My pull request is atomic and focuses on a single change.
- [X] I have thoroughly tested my changes with multiple different prompts.
- [X] I have considered potential risks and mitigations for my changes.
- [X] I have documented my changes clearly and comprehensively.
- [X] I have not snuck in any "extra" small tweaks changes

### CODE REVIEW

**Comment by josephcmiller2** [comment]
Btw, I have a series of test prompts that I will be submitting separately under tests/prompt_tests that can be used as a baseline to ensure what works now doesn't break with new changes.

**Review by nponeccop — DISMISSED** [review]

**Comment by nponeccop** [comment]
@josephcmiller2 There are conflicts now

**Review by nponeccop — APPROVED** [review]

**Review by richbeales — APPROVED** [review]

**Comment by richbeales** [comment]
please solve conflicts

**Comment by josephcmiller2** [comment]
Now obsolete due to the new '--skip-reprompt' feature.

**Pull request closed without merging**
