### PR TITLE
Missing article typo in README

### PR DESCRIPTION
**Pull request by MalikMAlna**
Just a small tweak with the README

### CODE REVIEW

**Review by nponeccop — CHANGES_REQUESTED** [review]
It's just a missing article. Make it clear in the PR ("Missing article typo in README") and squash 5 commits to 1. You can also extend the scope, e.g. the capitalization of Google API is inconsistent throughout the README, you can fix it.

**Comment by MalikMAlna** [comment]
I can, but the fact that I'm getting pushback for a single article change on a README inclines me toward not doing so. 

Also, @nponeccop a person with maintainer access can squash and merge by clicking on the triangle icon next to the merge button and selecting the squash and merge option. It's far easier for them to do that than for me to take the extra steps to squash and merge on my end while also doing the extra work to add more capitalization changes, extending the scope of this small and simple change.

Furthermore, if I do extend the scope of this change, I would have to change the PR title again to something more appropriate. So instead of doing all that I'd rather keep the scope relatively simple, change the title of the PR to what you suggested, and get this relatively simple change merged in without needlessly overcomplicating it.

After a week of waiting for such a small change, I think that makes sense. I hope you would agree.

**Review by nponeccop — APPROVED** [review]

**Comment by nponeccop** [comment]
Well, this repo suffers from organizational issues, so I'm trying to make it easier for the sole maintainer of @Torantulino to merge as many PRs a day as possible. Hopefully this resolves soon with a migration to an organizational repository when there are more granular permissions so he can give us a right to merge.

**Comment by MalikMAlna** [comment]
Totally fair @nponeccop; I completely understand. 

I hope that gets resolved for you all soon. Stuff like this should be relatively easy for you all to quickly merge, but given the current PR backlog, I can understand that being difficult when merge perms can't be sufficiently and easily delegated.

**Review by Torantulino — APPROVED** [review]

**Pull request merged**
