### PR TITLE
 Style change: replace unnecessary imports

### PR DESCRIPTION
**Pull request by AndresCdo**
### Background

I was looking there were many libraries needed to run this project. However, there are many imports that actually are not needed at all.

### Changes

I did change many files and imported just necessary imports.

### Test Plan

There is no test plan for these changes.

### CODE REVIEW

**Comment by nponeccop** [comment]
The PR content doesn't match its description. You don't remove redundant import statements.

Instead, you replace qualified imports (such as `os.foo`) with unqualified (`foo`).

This is a style change, and just changing a style for no other reasons is a bad idea. Stick to whatever the project uses, make it consistent throughout the codebase.

I vote for closing as not adding value. @Torantulino ?

**Comment by AndresCdo** [comment]
> The PR content doesn't match its description. You don't remove redundant import statements.
> 
> Instead, you replace qualified imports (such as `os.foo`) with unqualified (`foo`).
> 
> This is a style change, and just changing a style for no other reasons is a bad idea. Stick to whatever the project uses, make it consistent throughout the codebase.
> 
> I vote for closing as not adding value. @Torantulino ?

Thank you for reviewing my PR and for your feedback. I appreciate your concern about style changes and agree that they should not be made without a good reason.

The reason behind my changes was to remove redundant imports, which can improve the code's readability and maintainability. In doing so, I replaced some qualified imports with unqualified ones, which I believe is a widely accepted coding style.

I understand the importance of consistency throughout the codebase, and my intention was to contribute to that by removing redundant imports and using a consistent coding style. However, I understand your concern about the unqualified imports, and I am open to modifying my changes to keep the qualified imports while still removing the redundant ones.

Thank you for taking the time to review my PR, and I look forward to your further feedback.

**Comment by nponeccop** [comment]
Resolve the conflicts or rebase on the current master.

**Review by nponeccop — DISMISSED** [review]
LGTM but it's the maintainer who will decide on the style

**Review by nponeccop — APPROVED** [review]

**Review by nponeccop — APPROVED** [review]

**Comment by richbeales** [comment]
closed as resolved by #1393

**Pull request closed without merging**
