### PR TITLE
dirtyjson -> json

### PR DESCRIPTION
**Pull request by Veylkh**
Fixes the missing UserDict (caused by migration from python 3.9 to ^3.10)

### CODE REVIEW

**Comment by Veylkh** [comment]
Fixes issue https://github.com/Torantulino/Auto-GPT/issues/65

**Comment by PhilipAD** [comment]
Wasn't the point of using the dirtyjson to clean non-standard JSON. I think this fix maybe prone to errors.

**Comment by Veylkh** [comment]
Imported the API key directly in the file to test it and indeed it doesn't seem to work properly anymore when not using `dirtyjson`:

```
NEXT ACTION:  COMMAND = Error: ARGUMENTS = string indices must be integers
SYSTEM:  Command Error: returned: Unknown command Error:
Warning: Failed to parse AI output, attempting to fix.
 If you see this warning frequently, it's likely that your prompt is confusing the AI. Try changing it up slightly.
Failed to fix ai output, telling the AI.
ENTREPRENEUR-GPT THOUGHTS: The AI's response was unreadable.
Error:
 Traceback (most recent call last): File "C:\Users\PC\Auto-GPT\scripts\main.py", line 81, in print_assistant_thoughts assistant_thoughts_reasoning) UnboundLocalError: local variable 'assistant_thoughts_reasoning' referenced before assignment
Warning: Failed to parse AI output, attempting to fix.
 If you see this warning frequently, it's likely that your prompt is confusing the AI. Try changing it up slightly.
Failed to fix ai output, telling the AI.
```

**Comment by Torantulino** [comment]
I think I might actually just merge this. It seems like dirtyjson isn't a good option.

**Review by Torantulino — APPROVED** [review]
Still works fine with gpt3.5 :)

**Pull request merged**
