### PR TITLE
Remove the duplicate debug modes functions

### PR DESCRIPTION
**Pull request by kinance**
### Background
Seeing the duplicate set debug mode function

### Changes
Remove the duplicates caused by Pull Requests

### Test Plan
Tested with --debug in a command line

### PR Quality Checklist
- [*] My pull request is atomic and focuses on a single change.
- [*] I have thouroughly tested my changes with multiple different prompts.
- [*] I have considered potential risks and mitigations for my changes.
- [*] I have documented my changes clearly and comprehensively.
- [*] I have not snuck in any "extra" small tweaks changes

### CODE REVIEW

**Comment by kinance** [comment]
@cryptidv please help review.

**Review by nponeccop — APPROVED** [review]

**Comment by cryptidv** [comment]
Looks good.

**Review by cryptidv — APPROVED** [review]

**Comment by kinance** [comment]
@cryptidv @nponeccop Sorry, pressed a wrong button to request reviews.

**Review by nponeccop — APPROVED** [review]

**Review by cryptidv — APPROVED** [review]

**Comment by nponeccop** [comment]
@kinance Resolve the conflicts please

**Comment by kinance** [comment]
@nponeccop I am making another attempt to remove the duplicate set debug mode functions that exist on latest HEAD now.
Please help review https://github.com/Torantulino/Auto-GPT/pull/786.

**Comment by Torantulino** [comment]
Merged #786, so closing this.

**Pull request closed without merging**
