### PR TITLE
Fix debug mode flag

### PR DESCRIPTION
**Pull request by Joe0**
Fixes the debug flag and makes current debug code use the debug flag from the config.

### CODE REVIEW

**Review by yousefissa — APPROVED** [review]
lgtm

**Review by ryanmac — APPROVED** [review]

**Comment by ryanpeach** [comment]
I also added a debug mode flag

https://github.com/Torantulino/Auto-GPT/pull/146

**Comment by nponeccop** [comment]
@Joe0 It got outdated. Resolve the conflicts.

**Review by nponeccop — APPROVED** [review]

**Comment by nponeccop** [comment]
@Joe0 It's outdated again due to other merges.

**Comment by nponeccop** [comment]
@Joe0 Can you check if it is still necessary and close if it is not?

**Comment by richbeales** [comment]
closing as now superseded.

**Pull request closed without merging**
