### PR TITLE
Improve Dockerfile with best practices and optimizations

### PR DESCRIPTION
**Pull request by sunnypranay**
**Background**

The existing Dockerfile in the project can be improved by incorporating best practices and optimizations, such as using a non-root user, setting appropriate environment variables, and reducing image size by disabling caching. These changes will make the Dockerfile more secure, efficient, and compliant with best practices.

**Changes**
- Added environment variables to prevent Python from buffering the output and to disable writing `.pyc` files.

- Created a non-root user named `appuser` to follow the principle of least privilege and updated the ownership of files and folders accordingly.

- Added the `--no-cache-dir` flag to the `pip install` command to prevent caching and reduce the image size.

- Updated the `COPY` command to set the appropriate user and group ownership for the copied files.

**Documentation**

The changes have been explained in this pull request description. The improved Dockerfile itself includes comments that explain the purpose of each command and environment variable.

**Test Plan**
1. Build the Docker image using the updated Dockerfile with the command `docker build -t improved-dockerfile .`.

2. Run a container using the newly built image with `docker run --rm -it improved-dockerfile`.

3. Verify that the application runs as expected within the container, and that any relevant functionality still works as intended.

**PR Quality Checklist**

- [x] My pull request is atomic and focuses on a single change.
- [x] I have thoroughly tested my changes with multiple different prompts.
- [x] I have considered potential risks and mitigations for my changes.
- [x] I have documented my changes clearly and comprehensively.
- [x] I have not snuck in any "extra" small tweaks changes

### CODE REVIEW

**Review by nponeccop — APPROVED** [review]

**Review by richbeales — APPROVED** [review]

**Comment by mikekelly** [comment]
This test plan didn't account for docker-compose usage, which it broke. This optimisation caused a bunch of regressions and didn't appear to provide any meaningful benefit.

**Comment by KissPeter** [comment]
--no-cache-dir is not necessary if PIP_NO_CACHE_DIR is set

**Comment by nponeccop** [comment]
@KissPeter You can switch to the Files Changed tab and do a code review commenting on the lines and even requiring changes. It doesn't require any privileges.

**Comment by nponeccop** [comment]
Well, it's too late here. But you can file an issue :)

**Comment by mikekelly** [comment]
@KissPeter all of this is cleaned up by https://github.com/Torantulino/Auto-GPT/pull/1199

**Pull request merged**
