### PR TITLE
logging activity and error in log files in addition to the console - attempt 2

### PR DESCRIPTION
**Pull request by fabricehong**
This is a re-submit of PR https://github.com/Torantulino/Auto-GPT/pull/434.

For the PR template, see the related PR

### CODE REVIEW

**Comment by fabricehong** [comment]
ready soon

**Comment by nponeccop** [comment]
We have stopped a few minutes ago, and are waiting for you actually.

**Comment by fabricehong** [comment]
thanks.. still solving merge conflicts. ready very soon

**Comment by fabricehong** [comment]
@nponeccop @p-i- done ! :)

**Review by nponeccop — APPROVED** [review]

**Review by richbeales — APPROVED** [review]
fantastic, thanks for this

**Comment by fabricehong** [comment]
woowwooo :D

**Pull request merged**
