### PR TITLE
Use ruff for linting

### PR DESCRIPTION
**Pull request by Aarif1430**
### Background
This pull request adds ruff as a linter to the project. Ruff is known for being an extremely fast linter and can be configured using ```ruff.toml```. This change will enhance the project's code quality and maintainability, as ruff will help catch potential errors and inconsistencies.

### Changes
The specific change made in this pull request is adding ruff as a linter to the project. This involved installing the ruff package and creating a ```ruff.toml``` file to configure the linter. Additionally, the project's existing codebase was modified to comply with ruff's rules and recommendations.

### Documentation
This change is documented in the project's README file, where instructions for configuring and using ruff have been added. 

### Test Plan
The functionality has been tested using various test cases to ensure that ruff is functioning correctly and catching potential errors.

### PR Quality Checklist
- [X] My pull request is atomic and focuses on a single change.
- [X] I have thoroughly tested my changes with multiple different prompts.
- [X] I have considered potential risks and mitigations for my changes.
- [X] I have documented my changes clearly and comprehensively.
- [X] I have not snuck in any "extra" small tweaks changes

### CODE REVIEW

**Comment by hugorodgerbrown** [comment]
I think you want to update the `ci.yml` as well, to replace the current flake8 linter in there?

**Review by nponeccop — APPROVED** [review]

**Comment by nponeccop** [comment]
@Aarif1430 There are conflicts now

**Comment by Aarif1430** [comment]
> @Aarif1430 There are conflicts now

Have resolved the conflict now.

**Review by nponeccop — APPROVED** [review]

**Comment by richbeales** [comment]
Thank you, but we will close this as we already have a linter (flake8)

**Pull request closed without merging**
