### PR TITLE
Create PULL_REQUEST_TEMPLATE.md

### PR DESCRIPTION
**Pull request by hunteraraujo**
### Background

Currently we have a mass amount of PRs and it is becoming difficult to look at all of them in an efficient manner. We need a standardized way to see what is going on in a PR to streamline reviewing.

### Changes

This PR adds a new GitHub template to allow the developer to quickly and easily provide the relevant information.

### Test Plan

Raise a PR and verify template works.

### Change Safety

- [ ] I have added tests to cover my changes
- [x] I have considered potential risks and mitigations for my changes

Screenshot 2023-04-06 at 10 00 55 AM

### CODE REVIEW

**Review by dschonholtz — DISMISSED** [review]
Great initial start on this. I imagine we'll find more things we'll want over time. But this is great for now.

**Review by dschonholtz — APPROVED** [review]

**Review by dwrtz — APPROVED** [review]
Thank you!

**Review by dschonholtz — APPROVED** [review]

**Comment by Torantulino** [comment]
Brilliant, thank you for adding this!

This will be a huge help.

**Review by Torantulino — APPROVED** [review]

**Comment by jmanhype** [comment]
I dont know where to add this but we need CMD prmpt access in the bot. Like let it do command prompt tasks

**Comment by jmanhype** [comment]
To further improve the JSON response format, consider the following suggestions:

1. Add a 'status' field: Introduce a 'status' field to indicate the state of the AI's operation, such as "success," "error," or "in_progress." This will help users easily understand the outcome and status of the AI's response.

2. Allow multiple commands: Modify the 'command' section to accommodate an array of commands, allowing the AI to execute multiple actions in a single response. This enhances the versatility and efficiency of the AI's communication.

3. Add a 'confidence' field: Introduce a 'confidence' field in the 'thoughts' section to indicate the AI's level of certainty in its response. This can help users gauge the reliability of the AI's suggestions and reasoning.

4. Improve error handling: Include an 'error' field that provides a detailed description of any errors or issues encountered during the AI's operation. This will enable users to better understand and address potential problems.

By implementing these suggestions, the JSON response format will be more informative, versatile, and user-friendly, leading to an enhanced experience for users interacting with the AI system.

**Pull request merged**
