### PR TITLE
Fixed broken cfg.debug calls in chat

### PR DESCRIPTION
**Pull request by javierbq**
### PR Quality Checklist
- [x] My pull request is atomic and focuses on a single change.
- [x] I have thouroughly tested my changes with multiple different prompts.
- [ ] I have considered potential risks and mitigations for my changes.
- [ ] I have documented my changes clearly and comprehensively.
- [x] I have not snuck in any "extra" small tweaks changes

### CODE REVIEW

**Review by mohandutt134 — APPROVED** [review]

**Comment by thegalluzz** [comment]
If I'm not mistaken there is the same bug in /scripts/json_parser.py

**Review by Bharateshwar — APPROVED** [review]

**Review by Bharateshwar — CHANGES_REQUESTED** [review]
/scripts/json_parser.py needs the change too.

**Review by VincentRoma — COMMENTED** [review]
LGTM

**Comment by 100xlongx** [comment]
json_parser.py line 94

**Comment by richbeales** [comment]
A duplicate of this has already been merged

**Pull request closed without merging**
