### PR TITLE
Update and rename .env.template to .env

### PR DESCRIPTION
**Pull request by GauravMalik19**
### PR Quality Checklist
- [ ] My pull request is atomic and focuses on a single change.
- [ ] I have thoroughly tested my changes with multiple different prompts.
- [ ] I have considered potential risks and mitigations for my changes.
- [ ] I have documented my changes clearly and comprehensively.
- [ ] I have not snuck in any "extra" small tweaks changes

### CODE REVIEW

**Comment by GauravMalik19** [comment]
Make list of Private Equity CFOs in USA

**Review by mkcastro — CHANGES_REQUESTED** [review]
please be careful with your API keys.

We don't want to rename .env.template to .env because .env.template acts as a placeholder for the project's keys and settings.

**Comment by 0FFFFFFF** [comment]
Realesed tokens. Lol

**Comment by nathanwchan** [comment]
who's gonna tell this person?

**Comment by christianohlzon** [comment]
Immediately log in on open ai and pinecone and reset your api keys. You can still see them in the git history

**Pull request closed without merging**
