### PR TITLE
Rename scripts to autogpt and inform users to run python autogpt/main.py

### PR DESCRIPTION
**Pull request by merwanehamadi**
### Background

Other PRs create a module called autogpt and then rename scripts to autogpt when needed.

### Changes

Instead let's do it in 2 steps.
step 1:
- rename everything called scripts into auto_gpt
- keep the scripts/main.py just to print: "Please run autogpt/main.py"

Step 2
- create the autogpt module

### Test Plan

Screenshot 2023-04-13 at 12 26 11 PM
Screenshot 2023-04-13 at 12 26 00 PM
Screenshot 2023-04-13 at 12 26 37 PM

### PR Quality Checklist
- [x] My pull request is atomic and focuses on a single change.
- [x] I have thoroughly tested my changes with multiple different prompts.
- [x] I have considered potential risks and mitigations for my changes.
- [x] I have documented my changes clearly and comprehensively.
- [x] I have not snuck in any "extra" small tweaks changes

### CODE REVIEW

**Review by 0xArty — APPROVED** [review]

**Comment by merwanehamadi** [comment]
@nponeccop @richbeales
I changed the strategy:
- step 1 merge this
- step 2 @richbeales can run python migrate_scripts_to_autogpt/migrate_scripts_to_autogpt.py
- step 3 @richbeales can push and merge immediately

Current users will be informed that they have to use another command thanks to the script.

**Comment by nponeccop** [comment]
I don't know Python so can't review. I only serve as a human linter. And @richbeales is already sleeping. He will respond tomorrow.

**Comment by merwanehamadi** [comment]
ok, could you approve ?

this PR is a script that @richbeales can run and it will rename the autogpt folder and its dependencies. This will allow to avoid having constant rebases.
Screenshot 2023-04-13 at 2 46 49 PM
Screenshot 2023-04-13 at 2 46 59 PM

I tested it again and it works.

Screenshot 2023-04-13 at 2 47 09 PM

**Review by nponeccop — APPROVED** [review]

**Review by 0xArty — APPROVED** [review]
I created a PR https://github.com/Torantulino/Auto-GPT/pull/1191 that does this change manually.

The script is a great idea.

I've checked this branch and tested it myself. It works 👍

**Comment by merwanehamadi** [comment]
thanks man, let's get this out, I can't wait. Literally this is the only way: it needs by @richbeales

**Pull request closed without merging**
