### PR TITLE
implements #13

### PR DESCRIPTION
**Pull request by ResourceHog**

### CODE REVIEW

**Comment by alreadydone** [comment]
The title could just be "implements #13" :)

**Comment by slavakurilyak** [comment]
This pull request (#36) by @ResourceHog proposes to merge 5 commits into the `master` branch. The changes affect 4 files and result in a net addition of 84 lines and a deletion of 31 lines. The main changes include:

1. **scripts/commands.py**: Minor import changes, with the addition of the `print_to_console` import from `util`.
2. **scripts/config.py**: Added a new `active_mode` property and the corresponding setter method `set_active_mode`.
3. **scripts/main.py**: 
   - Removed the original `print_to_console` function and replaced it with the one imported from `util`.
   - Added a new `ACTIVE_MODE` argument to the `Argument` Enum.
   - Updated the `parse_arguments` function to handle the new `active_mode` configuration.
   - Added a new block of code to handle the active mode, which prompts the user to authorize or reject the command execution with a reason for rejection.
4. **scripts/util.py**: This is a new file containing the `print_to_console` function, which has been moved from `main.py`.

It would be great to see an updated **README.md** to reflect "Active Mode".

**Comment by Torantulino** [comment]
I want to implement this!
Mind bringing it up to date @ResourceHog?

**Comment by ResourceHog** [comment]
Yeah, will get to it tonight. Basically just need to test it in the new docker environment before pushing it.

**Review by Provello — DISMISSED** [review]

**Comment by ResourceHog** [comment]
Power went out as I was working on this. Will have to wait till tomorrow.

**Review by MerwaneHAMADI — APPROVED** [review]

**Comment by ResourceHog** [comment]
It seems a bit redundant now that user input has been implemented in another pull request. Oh well, that happens sometimes!

**Pull request closed without merging**
