### PR TITLE
Elevenlabs voice ID

### PR DESCRIPTION
**Pull request by dillweed**
### Background
This pull request adds the option to use custom elevenlabs.io voice IDs in the `.env` file which is loaded by `config.py` and referenced by the `speak.py` module.  The existing default voice IDs within `speak.py` will be used if custom values are not provided.

### Changes
- Updated `.env.template` with environment variables for two optional voice IDs.
- Updated `config.py` to retrieve custom voice IDs from environment variables.
- Updated `speak.py` to use custom voice IDs if available and use default voice IDs if custom values are not provided.
- Added a check for placeholder values in voice IDs.

### Documentation
The changes are documented in the in-code comments and follow the existing code style.

### Test Plan
- Tested with custom voice IDs provided in the `.env` file.
- Tested without providing voice IDs in the `.env` file.

### PR Quality Checklist
- [x] My pull request is atomic and focuses on a single change.
- [x] I have thoroughly tested my changes with multiple different prompts.
- [x] I have considered potential risks and mitigations for my changes.
- [x] I have documented my changes clearly and comprehensively.
- [x] I have not snuck in any "extra" small tweaks changes

### CODE REVIEW

**Review by Torantulino — APPROVED** [review]

**Comment by AdelElo13** [comment]
nice guys now we have to search for voice id instead of making it more simple you guys make it harder to use

**Comment by austinmw** [comment]
How can I add a cloned voice? Specifying `cloned/<name>` doesn't work.

**Comment by dillweed** [comment]
> How can I add a cloned voice? Specifying `cloned/<name>` doesn't work.

If you have already made a custom Eleven Labs cloned voice, you can get the ID through an API call. https://docs.elevenlabs.io/guides/text-to-speech

There are also some premade voices to select from. Try their demos to find one you like.

**Comment by austinmw** [comment]
Strange, the Get Voices API call doesn't seem to list the voices I created, only the premade ones.

**Comment by dillweed** [comment]
> Strange, the Get Voices API call doesn't seem to list the voices I created, only the premade ones.

To retrieve a custom voice ID, you have to supply the API key associated with the custom voice.

**Comment by austinmw** [comment]
Ah, got it, thanks!

**Comment by hardhands** [comment]
where is the id though? can't see it anywhere - unless it's right in front of me??

**Comment by hardhands** [comment]
hm ok I had to use the api https://api.elevenlabs.io/docs#/voices/Get_voices_v1_voices_get to get them

**Pull request merged**
