### PR TITLE
fix for using GPT4 in gpt3only mode

### PR DESCRIPTION
**Pull request by T-Lycett**
explicitly pass the model we want to use to call_ai_function

### CODE REVIEW

**Review by ryanmac — APPROVED** [review]
This. I made the same changes.

**Review by OannesGPT — APPROVED** [review]
Made a github account to write that I implemented this as my first python code and it worked. I no longer have the missing plugin message

**Review by Mack0438 — APPROVED** [review]

**Comment by sberney** [comment]
I thought I noticed a bug that behaved like what this could cause. But when I look at the changeset, I don't see why this fixes it. What am I missing?

**Comment by T-Lycett** [comment]
this is a better fix:
https://github.com/Torantulino/Auto-GPT/pull/321

**Pull request closed without merging**
