### PR TITLE
Refactor main as a class to allow programmatic access

### PR DESCRIPTION
**Pull request by jlivni**
### Background
When running main.py, all variables are reset and the interaction loop automatically starts.  This makes it difficult/impossible to wrap the existing main.py in another program and access the partial results. In addition, if there is any crash, it's not possible to pick up where you left off.  

By refactoring main.py to run as a class, we can keep existing functionality, follow a more standard python 
approach, and allow someone to do something like ```import main; ag=AutoGPT()``` and then in case of a crash still access the partial results in the `ag` variable.

### Changes
The main.py code was refactored to be within an AutoGPT class, which is by default called with run_main_loop=True, keeping existing functionality.  No functionality was changed, but many lines were changed (mostly due to indentation).  Other lines were changed solely to call `self.foo()` instead of just `foo()`, or add `self` as the first parameter to functions within the class.

### Documentation
There is no additional new documentation.

### Test Plan
I ran through 100 iterations of the standard flow (`python scripts/main.py`) with multiple prompts, and tested config params worked.  I tested also with prompts that complete the task.

### PR Quality Checklist
- [x ] My pull request is atomic and focuses on a single change.
- [x] I have thoroughly tested my changes with multiple different prompts.
- [x] I have considered potential risks and mitigations for my changes.
- [x] I have documented my changes clearly and comprehensively.
- [x] I have not snuck in any "extra" small tweaks changes

### CODE REVIEW

**Comment by jlivni** [comment]
@Torantulino LMK if you are interested in this PR and I will keep it up to date -- it's a bit tricky since main.py changes a lot.  No worries if not and I won't spend the effort.

**Comment by nponeccop** [comment]
@jlivni There are no plans to merge things like this before we drain the PR queue. @ryanmac @p-i- @Torantulino ?

**Comment by ryanmac** [comment]
I agree with @nponeccop. I like the direction, but merging existing PRs will be difficult. Migrating after the existing PRs seems less painful.

**Comment by jlivni** [comment]
Thanks that makes sense.  I am closing this PR and will re-open when things calm down in your queue.  Appreciate all your work.

**Pull request closed without merging**
