### PR TITLE
More logical Prompt - found by Agusx1211

### PR DESCRIPTION
**Pull request by thepok**
This way it thinks befor it acts

### CODE REVIEW

**Comment by PhilipAD** [comment]
This is could good idea.

Conversely, if the action is before the thoughts then the thoughts are more likely to tend toward the actions generated.

**Review by PhilipAD — APPROVED** [review]

**Review by Legoteam986 — APPROVED** [review]

**Review by TrshDesigns — APPROVED** [review]
This should do the job

**Comment by vjdad4m** [comment]
Good idea as GPT generates the text token-by-token, so having the thoughts before the action is logical.

**Review by Arlodotexe — APPROVED** [review]
Lgtm!

**Review by amauryfischer — APPROVED** [review]

**Review by Void-n-Null — APPROVED** [review]

**Review by vjdad4m — APPROVED** [review]

**Comment by AzureDominus** [comment]
What a great idea! Small change but a big difference!

**Comment by Torantulino** [comment]
This is genius. I love these simple, outside-the-box solutions.

**Review by Torantulino — APPROVED** [review]

**Pull request merged**
