### PR TITLE
Add Virtual Environment Support and Update README

### PR DESCRIPTION
**Pull request by slavakurilyak**
This pull request introduces support for Python 3.8 virtual environments and updates the README with instructions on creating and activating a virtual environment. Additionally, the `.gitignore` file has been updated to ignore the "auto_gpt_workspace" folder.

### CODE REVIEW

**Comment by nponeccop** [comment]
This just makes things complicated for non-pythoners. So it may be an alternative setup for purists, but the primary setup should be as simple as possible, sacrificing some conceptual goodness for simplicity.

**Review by mkcastro — APPROVED** [review]

**Review by nponeccop — COMMENTED** [review]
This is a very large PR that touches literally everywhere. It's up to @Torantulino to decide if we should split it.

**Comment by slavakurilyak** [comment]
I made changes only to README. I don't know why other files were pulled in here. Closing this for now.

**Comment by nponeccop** [comment]
Then you could just rebase it against the current master.

**Pull request closed without merging**
