### PR TITLE
If you use autopep8 now, you will break all PR's

### PR DESCRIPTION
**Pull request by ryanpeach**
I don't think we can safely run black or autopep8 on this repo since there are so many contributions. Best we can do is fix manually with flake8.

### CODE REVIEW

**Comment by ryanpeach** [comment]
https://github.com/Torantulino/Auto-GPT/issues/137

**Comment by ryanpeach** [comment]
I think you should still delete this file. It's breaking PR workflows right now, and you shouldn't do git commit's in workflows, you should only check for formatting. Formatting application should be done in a pre-commit file.

**Review by nponeccop — APPROVED** [review]
I agree. Committing in CI (and under a person's name) is a bad idea. CI should only prevent a merge, not do changes on its own.

**Comment by richbeales** [comment]
closed as resolved by #1393

**Pull request closed without merging**
