### PR TITLE
In response to #796.  Added Chatbox Functionality in Browser.  Chat with custom data.

### PR DESCRIPTION
**Pull request by Nnnsightnnn**
Here's a link to the fork - [https://github.com/Nnnsightnnn/Auto-GPT-1](url)

## Background
In reference to [https://github.com/Torantulino/Auto-GPT/issues/796](url) which focused on the model exceeding it's token limit. 

Investigate solutions to chat with AI over large datasets.  If this proves valuable, will utilize the data_structure.py to integrate with preprocessing data and then saving it to a database for Auto-GPT to utilize later.

These additional modules allow for .txt and .HTML.  Have not tested if you can use it with .pdf files yet.  I did not make changes to the browse_website data.   This is more of a solution for this issue that relies on additional scripts not in main.py.   The change would be creating a script, data_structure.py, that can consume the data and then pass to other scripts for use.   The following are scripts that can be utilized to build a path for Auto-GPT to search a custom database in addition to utilizing web data.  

Here's an Excalidraw of the concept:

image

### Added:

- data_structure.py    _this script allows flask app to get file and embeds data_
- llm_handler.py    _this script allows the flask app  to send and receive to a chat box_
- app.py   _this script launches a chatbot inside a local browser_
- templates/index.html    _this file contains the structure for the web page_
- static/API documentation    _ Alpha Vantage.html _this file contains the data from the issue that wasn't resolved_
- static/chatbot_droids.jpg    _this file contains a picture created using Midjourney, can be swapped out you just have to change HTML to a different picture_
- static/styles.css _this file contains the styles for the html_

### Modifications to:

-ai_config.py      _added knowledgebase lines to _
-ai_settings.yaml     _added lines for knowledgebase_

## Documentation

**To** utilize the Chat-bot
`python scripts/app.py`
_Let the module run then open browser when prompted_

### Here are some of the changes made to ai_config
`    def __init__(self, ai_name: str="", ai_role: str="", ai_goals: list=[], knowledgebase: str="") -> None:
        """
        Initialize a class instance

        Parameters:
            ai_name (str): The name of the AI.
            ai_role (str): The description of the AI's role.
            ai_goals (list): The list of objectives the AI is supposed to complete.
            knowledgebase (str): filename
        Returns:
            None
        """

        self.ai_name = ai_name
        self.ai_role = ai_role
        self.ai_goals = ai_goals
        self.knowledgebase = knowledgebase

    # Soon this will go in a folder where it remembers more stuff about the run(s)
    SAVE_FILE = os.path.join(os.path.dirname(__file__), '..', 'ai_settings.yaml')

    @classmethod
    def load(cls: object, config_file: str=SAVE_FILE) -> object:
        """
        Returns class object with parameters (ai_name, ai_role, ai_goals, knowledgebase) loaded from yaml file if yaml file exists,
        else returns class with no parameters.

        Parameters:
           cls (class object): An AIConfig Class object.
           config_file (int): The path to the config yaml file. DEFAULT: "../ai_settings.yaml"

        Returns:
            cls (object): A instance of given cls object
        """

        try:
            with open(config_file) as file:
                config_params = yaml.load(file, Loader=yaml.FullLoader)
        except FileNotFoundError:
            config_params = {}

        ai_name = config_params.get("ai_name", "")
        ai_role = config_params.get("ai_role", "")
        ai_goals = config_params.get("ai_goals", [])
        knowledgebase = config_params.get("knowledgebase", "")`

## Test Plan
I've run multiple sessions with the Chatbot on the received document.  The document is quite long, so I'm sure this module can accept documents of lesser sizes.  Here's some of the conversations I had with the bot. 

image

image

## Risks
-Introduces additional features that aren't directly tied to CLI functionalities.
-Introduces additional features that have to be maintained.

## Benefits
-Offers a way for users to chat with ai utilizing custom database

## Future Plans
- In the future, would like to integrate data_structure into agent_manager...and allow agent_manager to decide when to use this method.  
- Either remove chatbot functionality or allow main.py to utilize Flask.

## PR Quality Checklist
- [x] My pull request is atomic and focuses on a single change.
- [x] I have thoroughly tested my changes with multiple different prompts.
- [x] I have considered potential risks and mitigations for my changes.
- [x] I have documented my changes clearly and comprehensively.
- [x] I have not snuck in any "extra" small tweaks changes 

Thank you for reviewing this Pull Request.  I'm enjoying working on this project.  Feedback is appreciated.

### CODE REVIEW

**Comment by Nnnsightnnn** [comment]
Need to resolve -r requirements file.  Additions are flask.

**Review by nponeccop — DISMISSED** [review]

**Comment by nponeccop** [comment]
@Nnnsightnnn There are conflicts now

**Comment by Nnnsightnnn** [comment]
> @Nnnsightnnn There are conflicts now

okay will look into

**Comment by Nnnsightnnn** [comment]
@nponeccop I have rebuilt the chat-bot.

### Added files
- /scripts/app.py    _contains flask application_
- /scripts/data_structure    _look in database folder for files.  Create vectorstore from files_
- scripts/llm_handler   _creates chat functionality for app.py_
- /scripts/database (folder)     _holds data to be sent to vectorstore_
- /database/restrict_act.txt    _test document S.686 - RESTRICT Act to chat with _
- /database/work_week.txt      _test document covering H. R. 1332 reduce the standard 
  workweek from 40 hours per week to 32 hours_
- API Documentation _ Alpha Vantage.html     _large test document covering API usage for Alpha Vantage_
- /scripts/templates/index.html   _code for webpage_
- /scripts/static/styles.css   _css code for styling webpage_
- /scripts/static/chatbot_droids.jpg    _background photo_

### Modified files
- requirements.txt  _added flask and langchain_

### Here's some test pictures

**Massive document splitting from database**

image


Chatting with bot about each file.

image


### In closing

The app.py script opens the flask application in a browser and will function separate from the rest of Auto-GPT until we have a good way to integrate the front end.  data_structure.py has several function that can be utilized outside of the app.py script.  My main motivation was to provide user with a structure to chat with custom data.  In future, I would like to integrate the full-functionality of Auto-GPT with the data_structure.py or some functionality similar.

Let me know if this helps...I've just checked to make sure there aren't any conflicts.

Thanks

**Comment by nponeccop** [comment]
@Nnnsightnnn There are conflicts now

**Pull request closed without merging**
