### PR TITLE
Flags Updates

### PR DESCRIPTION
**Pull request by cryptidv**
### Background
The Auto-GPT script should be more user friendly and more "scriptable" so to speak.

### Changes
Added the following flags:
* `--skip-reprompt` (`-y`) - Skips the Auto-GPT re-prompt message if the `ai_setting.yaml` file exists. Helpful for testing.
* `--ai-settings` (`-C`) - Allows the user to pass through a separate AI Settings file. Useful to quickly switch between AI Configurations, etc. (Also reads value from the `AI_SETTINGS_FILE` environment variable, if user wants to specify non-default file without using the flag every time). Will also skip the re-prompt.
* Added a shorthand for `--continuous`: `-c`
* Fixed the error logging with `--use-memory` flag. Changed `print_to_console()` -> `logger.typewriter_log()`

**Note:** the program will validate if the user-provided AI Settings files are correct. It does this by checking for the files existence and ensures the YAML can be read and loaded properly.

### Test Plan
Tested by running each flag individually and with each other, everything seems to work correctly. If people could also help test on other systems (Linux, MacOS, etc.) that would be great!

### PR Quality Checklist
- [x] My pull request is atomic and focuses on a single change.
- [x] I have thoroughly tested my changes to the best of my ability
- [x] I have considered potential risks and mitigations for my changes.
- [x] I have documented my changes clearly and comprehensively.
- [x] I have not snuck in any "extra" small tweaks changes

### CODE REVIEW

**Review by nponeccop — APPROVED** [review]

**Review by nponeccop — APPROVED** [review]

**Comment by richbeales** [comment]
I think .env.template and README.md should be altered to surface your changes to the user.

**Comment by nponeccop** [comment]
@cryptidv There are conflicts now

**Comment by cryptidv** [comment]
> I think .env.template and README.md should be altered to surface your changes to the user.

Done.

@nponeccop Everything should be resolved now

**Comment by cryptidv** [comment]
@richbeales Would it be an idea to include a flag that would create an example `ai_settings.yaml` for user reference? Or include an examples folder where we can store example files?

**Review by nponeccop — APPROVED** [review]

**Review by richbeales — APPROVED** [review]

**Pull request merged**
