### PR TITLE
Fix to LocalCache add method, created integration test for it

### PR DESCRIPTION
**Pull request by nerzhul250**
vector should be added at the end of embeddings
Created an integration test for localCache

### Background

Just noticed that the get_relevant method from LocalCache would return not the top k relevant texts but the least k relevant

### Changes

vector embedding is added at the end of the embeddings list
Created a simple integration test to check that flow
Proposed a simple folder structure to handle unit and integration tests

### Test Plan

Created a simple integration test that:
1. Config is initialized with current env variables
2. examples texts are added to the list of embeddings (plus some noisy ones)
3. we query the top 3 relevant texts to the query text.

### Change Safety

- [x] I have added tests to cover my changes
- [x] I have considered potential risks and mitigations for my changes

Created PR again because force pushing closes PRs (#603)

### CODE REVIEW

**Review by nponeccop — APPROVED** [review]
I guess it's a clean version of an earlier PR? This time LGTM

**Comment by BillSchumacher** [comment]
Good catch =)

**Review by Torantulino — APPROVED** [review]
Good catch, and great work on the testing!

**Comment by Torantulino** [comment]
Sorry @nerzhul250 can you resubmit this?
I accidentally merged it in to the wrong branch.

**Comment by nponeccop** [comment]
You can just merge his commit into the right branch in git command line. This will preserve commit attribution.

**Comment by Torantulino** [comment]
Nice, thank you, all merged now

**Pull request merged**
