### PR TITLE
Add data_ingestion.py script for memory pre-seeding

### PR DESCRIPTION
**Pull request by maiko**
### Background
This pull request aims to implement a new feature in Auto-GPT. The feature was previously discussed on Discord.

Memory pre-seeding is a technique that involves ingesting relevant documents or data into the AI's memory so that it can use this information to generate more informed and accurate responses.

To pre-seed the memory, the content of each document is split into chunks of a specified maximum length with a specified overlap between chunks, and then each chunk is added to the memory backend set in the .env file. When the AI is prompted to recall information, it can then access those pre-seeded memories to generate more informed and accurate responses.

### Changes
The specific change made in this pull request is the addition of a new script, data_ingestion.py, which allows users to ingest relevant documents or data into memory for pre-seeding by spliting the content of each file into chunks of a specified maximum length with a specified overlap between chunks, and then adds each chunk to the memory backend set in the .env file. 

The pull request also includes updates to the project's documentation to explain how to use the new feature and its benefits.

### Documentation
The changes made in this pull request are well-documented, both through in-code comments and external documentation. 
The README.md file has been updated to include a detailed explanation of the new feature, how to use the data_ingestion.py script, and how to adjust the relevant parameters. The documentation is clear, concise, and easy to understand, ensuring that users can quickly and easily take advantage of the new feature.

```
python3.exe .\scripts\data_ingestion.py --dir seed_data --overlap 100 --max_length 4000
Using memory of type: RedisMemory
Working with file seed_data\README.md
File length: 20963 characters
Ingesting chunk 1 / 6 into memory
Ingesting chunk 2 / 6 into memory
Ingesting chunk 3 / 6 into memory
Ingesting chunk 4 / 6 into memory
Ingesting chunk 5 / 6 into memory
Ingesting chunk 6 / 6 into memory
Done ingesting 6 chunks from seed_data\README.md.
Directory 'seed_data' ingested successfully.
```

### Test Plan
Ingest some files and ask Auto-GPT some questions or ingest data that can help it acheive its objectives and watch as it "recall" those informations from memory.

```
  ------------ CONTEXT SENT TO AI ---------------
  System: The current time and date is Wed Apr 12 22:40:59 2023
  
  System: This reminds you of these events from your past:
[]


  User: Determine which next command to use, and respond using the format specified above:

  ----------- END OF CONTEXT ----------------
THINKINGISTHEKEY THOUGHTS:  I need to think about what Auto-GPT is and answer the question 'What is Auto-GPT?'
REASONING:  I cannot provide an answer without understanding what Auto-GPT is first. I need to gather information from my long term memory and explore any available resources
PLAN:
-  Search the text in my long term memory for keywords related to Auto-GPT,
-  Access any available resources such as websites or documents for information about Auto-GPT
CRITICISM:  I need to be mindful not to become distracted by irrelevant information and to efficiently acquire information that will help me understand what Auto-GPT is
NEXT ACTION:  COMMAND = do_nothing ARGUMENTS = {}
Enter 'y' to authorise command, 'y -N' to run N continuous commands, 'n' to exit program, or enter feedback for ThinkingIsTheKey...
Input:y
-=-=-=-=-=-=-= COMMAND AUTHORISED BY USER -=-=-=-=-=-=-= 
SYSTEM:  Command do_nothing returned: No action performed.

[...]
  ------------ CONTEXT SENT TO AI ---------------
  System: The current time and date is Wed Apr 12 22:41:13 2023

  System: This reminds you of these events from your past:
['Filename: seed_data\\README.md\nContent part#1/6: # Auto-GPT: An Autonomous GPT-4 Experiment\n\n![GitHub Repo stars]

[...]

  User: GENERATE NEXT COMMAND JSON

  ----------- END OF CONTEXT ----------------
THINKINGISTHEKEY THOUGHTS:  Auto-GPT is a language model driven autonomous system that chains together LLM "thoughts". I found this information in my long term memory. I can use this information to answer the question 'What is Auto-GPT?'
REASONING:  Auto-GPT being an autonomous system that chains together LLM thoughts enables the system to operate fully autonomously, making use of GPT-4 Language Model to achieve specific goals. I can use this understanding to answer the question "What is Auto-GPT?"
PLAN:
-  Answer the question "What is Auto-GPT?"
CRITICISM:  I should ensure that my answer is clear, concise and focused on the question being asked.
NEXT ACTION:  COMMAND = write_to_file ARGUMENTS = {'file': 'Auto-GPT-answer.txt', 'text': 'Auto-GPT is an autonomous system that chains together LLM "thoughts" using GPT-4 Language Model to achieve specific goals.'}
Enter 'y' to authorise command, 'y -N' to run N continuous commands, 'n' to exit program, or enter feedback for ThinkingIsTheKey...
Input:y
```

### PR Quality Checklist
- [x] My pull request is atomic and focuses on a single change.
- [x] I have thoroughly tested my changes with multiple different prompts.
- [x] I have considered potential risks and mitigations for my changes.
- [x] I have documented my changes clearly and comprehensively.
- [x] I have not snuck in any "extra" small tweaks changes

### CODE REVIEW

**Comment by estiens** [comment]
I believe you can only ingest files in your workspace correct? Can you add that to the readme?

**Comment by maiko** [comment]
> I believe you can only ingest files in your workspace correct? Can you add that to the readme?

Yes. It's already in there at line 290. 😀

**Review by nponeccop — DISMISSED** [review]

**Comment by nponeccop** [comment]
@maiko There are conflicts again

**Comment by maiko** [comment]
Conflicts resolved.

**Review by nponeccop — DISMISSED** [review]

**Comment by richbeales** [comment]
A few linting errors then this can go in

scripts/data_ingestion.py:9:1: E302 expected 2 blank lines, found 1
scripts/data_ingestion.py:47:5: E303 too many blank lines (2)
scripts/file_operations.py:45:1: E302 expected 2 blank lines, found 1

**Comment by maiko** [comment]
Linting should be good now

**Review by nponeccop — DISMISSED** [review]

**Comment by maiko** [comment]
conflict resolved

**Review by richbeales — APPROVED** [review]

**Comment by heyalexchoi** [comment]
very cool feature. is this expected to work with pinecone memory? I'm trying it out right now. have tried with a directory and a repo readme file. testing by asking the active auto-gpt instance f"what is {subject}? do not use google" but unfortunately it does not seem to know.

**Pull request merged**
