### PR TITLE
cfg.debug -> cfg.debug_mode

### PR DESCRIPTION
**Pull request by AdrianScott**
### Background
Auto-GPT/scripts/chat.py", line 67, in chat_with_ai
    if cfg.debug:
AttributeError: 'Config' object has no attribute 'debug'

encountered this error message

### Changes
cfg.debug: -> cfg.debug_mode in 3 occurrences in chat.py and one occurence in json_parser.py

### Documentation
not applicable

### Test Plan
re-ran script and error no longer occurs

### PR Quality Checklist
- [x] My pull request is atomic and focuses on a single change.
- [x] I have thouroughly tested my changes with multiple different prompts.
- [x] I have considered potential risks and mitigations for my changes.
- [x] I have documented my changes clearly and comprehensively.
- [x] I have not snuck in any "extra" small tweaks changes

### CODE REVIEW

**Review by yantxs — APPROVED** [review]

**Comment by richbeales** [comment]
superseded by https://github.com/Torantulino/Auto-GPT/pull/818 which has now been merged

**Comment by SuperYeti** [comment]
Looks like this was pushed and commited earlier today: https://github.com/Torantulino/Auto-GPT/commit/e0cb648858427dfa2dc3b31b7485791707e981cd this PR can be closed.

**Comment by richbeales** [comment]
a duplicate of this has already been merged

**Comment by AdrianScott** [comment]
Yes, thanks!

**Pull request closed without merging**
