### PR TITLE
pull image if it's not found locally

### PR DESCRIPTION
**Pull request by nolan23**
### Background

If the given image is not found locally, the code will be stuck

### Changes
using docker api to get the image in local, if not found then pull the image from docker hub. I also log progress when pulling so user can see the progress 

### Documentation
I have specify some comments inside execute_python_file

### Test Plan

manual test:
- run python script with docker version that not exist in local
- it should not be stuck
- it should pull the image from docker hub
- it should show the progress
- it should able to continue executing the code

### PR Quality Checklist
- [x] My pull request is atomic and focuses on a single change.
- [x] I have thoroughly tested my changes with multiple different prompts.
- [x] I have considered potential risks and mitigations for my changes.
- [x] I have documented my changes clearly and comprehensively.
- [x] I have not snuck in any "extra" small tweaks changes

### CODE REVIEW

**Comment by selvaggi** [comment]
why is docker required here anyway?

**Comment by nolan23** [comment]
> why is docker required here anyway?

it's for `execute_python_file`

**Comment by selvaggi** [comment]
I meant but why can't the script be executed using locally installed python?

**Comment by nolan23** [comment]
> I meant why can't the script be executed using locally installed python?

we can use locally installed python instead of docker for sure. but in my opinion, by delegating the code execution to docker, we're free to adjust the environment to our needs, such as the python version. and since it's run inside container, it won't affect our current running script when the python needs to install dependency

**Comment by Lyx52** [comment]
> I meant why can't the script be executed using locally installed python? 

Additionally its more secure this way, we cant be sure what kind of code the Agents will try to run... Could be destructive...

**Review by richbeales — APPROVED** [review]

**Pull request merged**
