### PR TITLE
Fix #803

### LINKED ISSUE #803: debug mode not debug
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

attribute in chat.py is not named correctly

### Current behavior 😯

wrong name can't call the attrb on the object

### Expected behavior 🤔

to use the attrb in a  call without error

### Your prompt 📝

```yaml
# Paste your prompt here

### PR DESCRIPTION
**Pull request by tvigouroux**
### Background
Correcting Bug #803 

### Changes
Changing cfg.debug to cfg.debug_mode in L67, 74 and 113 in chat.py

### PR Quality Checklist
- [X] My pull request is atomic and focuses on a single change.
- [X] I have thouroughly tested my changes with multiple different prompts.
- [X] I have considered potential risks and mitigations for my changes.
- [X] I have documented my changes clearly and comprehensively.
- [X] I have not snuck in any "extra" small tweaks changes

### CODE REVIEW

**Comment by Kenshiro-28** [comment]
Thank you for the pull request. I think you also need to change the name in json_parser.py, line 94

**Review by levygrunwald — APPROVED** [review]
This looks good, bug fix is important latest Master version does not run.

**Review by jaspythonis — DISMISSED** [review]

**Comment by hanskraut31312312** [comment]
Traceback (most recent call last):
  File "scripts/main.py", line 321, in <module>
    assistant_reply = chat.chat_with_ai(
  File "C:\Programming\Auto-GPT_AI_8\scripts\chat.py", line 67, in chat_with_ai
    if cfg.debug:
AttributeError: 'Config' object has no attribute 'debug'

Down since 2-3 hours will check this out...

**Comment by tvigouroux** [comment]
> Thank you for the pull request. I think you also need to change "cfg.debug" to "cfg.debug_mode" in json_parser.py, line 94

You are right. I added this change to this PR

**Review by sumukhah — APPROVED** [review]

**Review by jaspythonis — APPROVED** [review]

**Review by nponeccop — APPROVED** [review]

**Comment by JesseRWeigel** [comment]
FWIW, I just tested this on Windows and it is working for me. Thanks for the fix! Has been stopping me from using this for a few days.

**Comment by chozzz** [comment]
Hi guys, I also added a similar fix at https://github.com/Torantulino/Auto-GPT/pull/888
I am happy to revert my changes regarding this area as it has the same changes, however this is missing this stub code at `scripts/main.py` in `parse_arguments`. I see this call was removed back in 186a8c615e1caeff2ffd13a4d0c74e7de56546ae
```
if args.debug:
        print_to_console("Debug Mode: ", Fore.GREEN, "ENABLED")
        cfg.set_debug_mode(True)
```

**Comment by richbeales** [comment]
closed as dupe already merged

**Pull request closed without merging**
