### PR TITLE
Fix the debug mode flag to set it in the config object and check properly

### PR DESCRIPTION
**Pull request by kinance**
### Background

Running the program with  --debug option to enable the Debug Mode does not work.

### Changes

1. Set the debug mode in the config object properly
2. Check the debug mode from the config object properly in the if conditions.

### Test Plan

1. Run the program with --debug parameter from the command line
2. Verify the correct debug messages in console

### Change Safety

- [ ] I have added tests to cover my changes
- [*] I have considered potential risks and mitigations for my changes

It's a simple change to make the debug mode work. It does not need a recession test case.

### CODE REVIEW

**Comment by nponeccop** [comment]
@kinance Can you resolve the conflicts?

**Review by Torantulino — APPROVED** [review]

**Comment by tlnet1981** [comment]
Sorry new to all this. Chapeau to all the contributers, coders, creators here!

since this commit i get an error:
\Auto-GPT\scripts\main.py", line 22, in check_openai_api_key
    if not cfg.openai_api_key:
NameError: name 'cfg' is not defined

Hope this helps

**Comment by AHorihuela** [comment]
Same here.

**Comment by AHorihuela** [comment]
Looks like it was just fixed with the latest merge.

**Pull request merged**
