### PR TITLE
Add unit tests workflow

### PR DESCRIPTION
**Pull request by drikusroor**
### Background
The last days we have seen quite some instability after some PRs had been merged, related to config properties, json parsing, infinite loops. This PR doesn't necessarily fix those issues but unit tests run in a workflow and is an attempt to try to set a first baseline for protecting the quality and desired functionality of the code. Additionally, it allows other developers to add new or change existing unit tests in a relatively straight-forward way.

### Changes
- Add a workflow that runs the unit tests after every commit on the `master` branch and for every PR targeted towards the `master` branch.
- Code coverage is also generated, but I haven't made a decision on how to report those (in a badge?). Perhaps that something for the owner(s) of this repository to decide.
- Fix the module imports for the existing unit tests.
- Fix some of the `json_parser` unit tests. 
- Add some unit tests for the `Config` class.
- Fix the `cfg.debug` issue that was [already](https://github.com/Torantulino/Auto-GPT/issues/803) reported earlier. These changes will probably "disappear" from the changed files once someone else's PR fixes it. (See also [here](https://github.com/Torantulino/Auto-GPT/pull/858), [here](https://github.com/Torantulino/Auto-GPT/pull/844/commits/c8de023ef4003776792ae8b6b365850a0df9bd2a), [here](https://github.com/Torantulino/Auto-GPT/pull/839), and [here](https://github.com/Torantulino/Auto-GPT/pull/835) 😅 )

### Documentation
- Pipeline status is documented in a badge in the beginning of `README.md`
- How to run the unit tests and the coverage variant is documented at the end of `README.md`

### Test Plan
The test plan is to create this PR and see if:
- The unit tests are running and succeeding
- The pipeline status badge is visible and working in `README.md`

### PR Quality Checklist
- [ ] My pull request is atomic and focuses on a single change.
- [ ] I have thouroughly tested my changes with multiple different prompts. (N/A)
- [X] I have considered potential risks and mitigations for my changes.
- [X] I have documented my changes clearly and comprehensively.
- [ ] I have not snuck in any "extra" small tweaks changes => Well, the `cfg.debug` issue was "snuck in". Please let me know if you want me to remove it.

### CODE REVIEW

**Review by richbeales — APPROVED** [review]

**Comment by richbeales** [comment]
Think we should add flake8 too

**Comment by drikusroor** [comment]
> Think we should add flake8 too

Do you want me to do that in this PR or in a separate PR after this one has been merged?

**Comment by richbeales** [comment]
If you're happy to, it'd be great to add it in a separate PR.

**Comment by MarjovanLier** [comment]
Let's go :)

**Comment by drikusroor** [comment]
> If you're happy to, it'd be great to add it in a separate PR.

I've added it in #923, but it's dependent on this PR since the whole workflow is added here. I think it'd be a good idea to first merge this (#865) PR and then the `flake8` PR (#923).

**Comment by richbeales** [comment]
@Torantulino would be good to get your eyes over this, and get this and 923 merged if you're happy?

**Review by richbeales — APPROVED** [review]

**Review by richbeales — APPROVED** [review]

**Pull request merged**
