### PR TITLE
Chaos/args format

### PR DESCRIPTION
**Pull request by 0xcha05**

### CODE REVIEW

**Comment by Torantulino** [comment]
This pull-request has 11 merge conflicts. 
Please merge `https://github.com/Torantulino/Auto-GPT.git` into your branch before submitting a pull request.

**Comment by 0xcha05** [comment]
resolved all merge conflicts.

**Comment by Torantulino** [comment]
image

This code contains Errors, please be sure to test thoroughly before submitting a pull request. 😊

**Comment by Torantulino** [comment]
> From your project repository, check out a new branch and test the changes.

`git checkout -b 0xcha05-chaos/args-format master`
`git pull https://github.com/0xcha05/Auto-GPT.git chaos/args-format`

**Comment by 0xcha05** [comment]
resolving merge conflicts from github web ui always is a mess 😅

**Comment by 0xcha05** [comment]
hopefully this pr works, https://github.com/Torantulino/Auto-GPT/pull/28

**Pull request closed without merging**
