### PR TITLE
Moved the scripts to a folder called auto-gpt

### PR DESCRIPTION
**Pull request by coleyr**
### Background

This PR is to re-organize the folder structure per pep8 standards, leaving room for a nice import auto-gpt vs import scripts. This also means windows users can use virtual environments without their files being added to the app python files. This was done with git mv so other PR's will be aware of the files moving vs a delete and recreate had the folder been renamed using the windows standard way of doing things.

### Changes

git mv ./scripts ./auto-gpt --> moves all scripts to a folder called auto-gpt
added readme instructions for a virtual environment, in my opinion the juice is worth the squeeze here
Adjusted the docker build file to pull in from the auto-gpt folder
Changed the name in the tests json import, this can be and should be altered once auto-gpt is made in one module.

### Test Plan
Need to build out robust unit test and validate tests for future PRs

### Change Safety

- [o] I have added tests to cover my changes
- [x] I have considered potential risks and mitigations for my changes

Working on a PR with unittests

### CODE REVIEW

**Comment by coleyr** [comment]
Also updated the .gitingore to be more inclusive and omit the scripts folder for people using venv

**Comment by ryanpeach** [comment]
So many people are doing the same thing. @Torantulino we need urgent decisions on this matter.

**Comment by ryanpeach** [comment]
@coleyr I've merged all your changes into https://github.com/Torantulino/Auto-GPT/pull/142

Can you please close your PR so we can consolidate all related efforts?

**Comment by WouterVH** [comment]
The proper solution is  src/auto_gpt

**Comment by coleyr** [comment]
Per RyanPeach merging the prs into one #142

**Comment by ryanpeach** [comment]
> The proper solution is src/auto_gpt

Python repos do not generally contain a src folder, especially if they only contain one module.

Common parlance is to provide one top level directory the same name as the repo.

If people want to vote over "autogpt" vs "auto_gpt" I think we can do that, but id rather get it merged in. I personally don't think the space is necessary.

**Comment by WouterVH** [comment]
For future reference:
>> Python repos do not generally contain a src folder, especially if they only contain one module.

The arguments have been clear for years.
There is just major lag and inertia caused by copy-pasting from projects that never properly looked into this.

References:
- https://github.com/pypa/packaging.python.org/issues/320
- https://blog.ionelmc.ro/2014/05/25/python-packaging/#the-structure
- https://hynek.me/articles/testing-packaging/
- https://packaging.python.org/en/latest/tutorials/packaging-projects/
- https://packaging.python.org/en/latest/discussions/src-layout-vs-flat-layout/

**Pull request closed without merging**
