### PR TITLE
Add Azure OpenAI Service support: specific deployment id by model. (re-submit PR from #580)

### PR DESCRIPTION
**Pull request by suensummit**
### Background

Since each deployment is created according to one specific model in Azure OpanAI Service, the deployment id should be specific by model.

### Changes

In `.env.template`, modify `OPENAI_AZURE_DEPLOYMENT_ID` to `OPENAI_AZURE_FAST_LLM_MODEL_DEPLOYMENT_ID` and `OPENAI_AZURE_SMART_LLM_MODEL_DEPLOYMENT_ID`.
Add a function `get_openai_deployment_id` in `llm_utils.py` to specific deployment id by model (fast/smart).
Also updated README.

### Documentation

This is a re-submit PR from #580

### Test Plan

It's more like a modification to fit API requirement, does not affect core functionality.

### PR Quality Checklist
- [x] My pull request is atomic and focuses on a single change.
- [x] I have thouroughly tested my changes with multiple different prompts.
- [x] I have considered potential risks and mitigations for my changes.
- [x] I have documented my changes clearly and comprehensively.
- [x] I have not snuck in any "extra" small tweaks changes

### CODE REVIEW

**Comment by suensummit** [comment]
@Torantulino review please, thanks

**Comment by sweetlilmre** [comment]
Hi, good to see someone else working on Azure integration.
The requirement for model selection by deployment id extends to the embedding code, see: https://github.com/Torantulino/Auto-GPT/pull/802
Perhaps it would be a plan to start some kind of generic model / deployment id config or mapping as the multiple .env entries are becoming a bit unwieldy. What are your thoughts?

**Comment by suensummit** [comment]
Hi @sweetlilmre yup there are example shows that we could create/retrieve/delete deployment programmatically: https://github.com/openai/openai-cookbook/blob/main/examples/azure/completions.ipynb
just need to handle the exception if the deployment with specific model is already exists (as Azure OpenAI allow only one deployment for each model currently.) and thus we should have a much smooth experience using Azure OpenAI.

**Comment by sweetlilmre** [comment]
In the meantime, I've added your idea into #802 and expanded it for the embedding model as well.

**Comment by suensummit** [comment]
> In the meantime, I've added your idea into #802 and expanded it for the embedding model as well.

This PR should be closed as #802 merged already ;)

**Pull request closed without merging**
