### PR TITLE
Remove `keys.py` and replace with `python-dotenv`

### PR DESCRIPTION
**Pull request by jcp**
- Removed `keys.py`.
- Added `.env.template`.
- Added `.env` to `.gitignore`.
- Updated various files that imported `keys` to use `os.getenv` instead.
- Updated `requirements.txt` dependencies and move to root directory.
- Updated README.md with instructions on setting up environment variables.

This change improves security, flexibility, and makes it easier to use Auto-GPT in notebooks. Environment variables are stored in `.env` and loaded via `load_dotenv()` in `scripts/main.py`.

### CODE REVIEW

**Comment by altryne** [comment]
The first thing I wanted to do since opening this repo 5 minutes ago, is this PR. 
Kudos to the author, LGTM, please merge

**Comment by altryne** [comment]
Added my api in .env, and getting this error:
CleanShot 2023-04-02 at 13 22 22@2x

**Comment by altryne** [comment]
All files apparently need load_dotenv for this to work, not only main.py 
I was able to fix this when I added 
```
import dotenv
dotenv.load_dotenv()

```

To both chat.py and speak.py

**Comment by jcp** [comment]
@altryne You're right. Typically that's not required. But given the way the app is structured, `load_dotenv()` needs to be called in `main.py`, `chat.py` and `speak.py`. I've pushed a fix: https://github.com/Torantulino/Auto-GPT/pull/39/commits/5e746afef8eb3f5bdb515eb918978abaf6276ea9.

Ideally, with some additional refactoring, this can be avoided.

**Review by Torantulino — APPROVED** [review]
Excellent work, thank you.

**Pull request merged**
