### PR TITLE
Features/support config file

### PR DESCRIPTION
**Pull request by dwrtz**
You can now configure Auto-GPT's name, role, and goals with a yaml config file:
```
python scripts/main.py --config_file=./scripts/example_config.yaml
```

### CODE REVIEW

**Comment by ryanmac** [comment]
As one who is constantly refining the objective and goals, this would be very valuable.

**Comment by peterarusanoff** [comment]
I would be using this feature allot vs having to copy paste in a million times

**Comment by Torantulino** [comment]
This feature already exists, but I take your point, I'll make that fact clearer.

**Comment by Torantulino** [comment]
Made clearer in #306

**Pull request closed without merging**
