### PR TITLE
Code quality workflows

### PR DESCRIPTION
**Pull request by kreneskyp**
@Torantulino 

This PR adds common code quality workflows. Goal is to provide a consistent sandbox environment for both local and github environments.

I based this off of https://github.com/Torantulino/Auto-GPT/pull/228 for the Dockerfile fixes it provided.

## Changes

- Github workflows that are optimized for build speed
    - Image is built and cached for re-use on subsequent runs
    - Cache key is based on hash of image inputs for re-use across similar branches
- Adds makefile for local build and testing
- Adds docker-compose file for adding other services to sandbox environment
- Adds pytest, flake8, black, pyright,  isort,  

## Testing:
- manual local testing of all tools/commands
- workflows debugged in my fork. Workflows are running but test runners fail because of errors found by each of them.
    https://github.com/kreneskyp/Auto-GPT/actions/runs/4630090599
    
    image

## TODO:
- need to add mounts for sound device and test that it works on windows, linux, mac

## For follow-up
- I recommend completing this PR and then fixing errors for each test runner in a separate PR.  Turn on branch protection for for each as they reach a passing state.

- It would be worth optimizing the image to make it a bit smaller.  It will be a bit friendlier to cache limits.

### CODE REVIEW

**Review by lcsmas — DISMISSED** [review]
LGTM

**Review by ksylvan — APPROVED** [review]
LGTM

**Review by nponeccop — CHANGES_REQUESTED** [review]
The scope is too big to sensibly merge. Split at least into 5 PRs:

- gitignore corrections
- updated docker build
- github CI
- readme typos, extra space and reformatting
- readme changes and additions

**Comment by nponeccop** [comment]
@kreneskyp Now it's out of date. Resolve the conflicts and split.

**Pull request closed without merging**
