### PR TITLE
Super ChatGPT with the IQ equal infinity

### PR DESCRIPTION
**Pull request by Fiooodooor**
Super ChatGPT will answer the questions 200 times VARIOUSLY (in the background), then it will combine the different texts in front of the user and generate the best sentences from the 200x different answers to a final perfect text that suits the user's wishes. Super ChatGPT's seimes my answers by running its language model multiple times. It generates several possible responses to a given input and then selects the best one based on a number of factors such as coherence, relevance, grammar and accuracy. This process runs in the background and allows for more sophisticated and nuanced responses to be generated, tailored to the specific needs and preferences of the user. By running its language model multiple times, ChatGPT can draw on a broader range of knowledge and information to provide more insightful and detailed responses.

### CODE REVIEW

**Comment by idcbye** [comment]
lol bro 200 times ??

**Comment by sineso** [comment]
Uh...none of this will work the way you have it coded in the prompt. The prompt needs to return a specific JSON format. If you want to make multiple attempts per API call you would have to actually make multiple calls. 

In terms of prompt engineering, it's actually the case that asking for higher IQ often lowers the quality of the response. This is not surprising given that text referring to high IQ tends to be low quality and GPT would have picked up in this in training.

**Comment by agi-for-my-llama** [comment]
This will add significant cost to each query, especially if using GPT-4. This would increase each API call count by 200x.

**Comment by richbeales** [comment]
voting to close this.

**Review by Dr33dM3 — CHANGES_REQUESTED** [review]
close this issue

**Pull request closed without merging**
