### PR TITLE
Continuous mode limit

### PR DESCRIPTION
**Pull request by josephcmiller2**
### Background
Continuous mode can run on too long without supervision and consume APIs unnecessarily. It would be helpful to have a limit to let it run unattended for a specified number of cycles.

### Changes
Add a command-line argument "--continuous-limit" that specifies the total number of execution loops in continuous mode thus limiting the amount that AutoGPT will run.

### Documentation
Code comments are included where needed.

### Test Plan
Tested multiple prompts with continuous mode, with continuous mode+limit, with no continuous mode but with limit (failed), and without any continuous mode at all. Program behaved as expected.

### PR Quality Checklist
- [X] My pull request is atomic and focuses on a single change.
- [X] I have thoroughly tested my changes with multiple different prompts.
- [X] I have considered potential risks and mitigations for my changes.
- [X] I have documented my changes clearly and comprehensively.
- [X] I have not snuck in any "extra" small tweaks changes

### CODE REVIEW

**Comment by richbeales** [comment]
arguably the same as using -y [x] where [x] is your 'continuous limit' as an answer to the first prompt.

**Review by nponeccop — APPROVED** [review]

**Comment by p-i-** [comment]
Don't think we should be printing 'Limit reached' in red -- red is best reserved for errors only.
If you'd like to fix that I'm happy to merge.

**Comment by josephcmiller2** [comment]
> Don't think we should be printing 'Limit reached' in red -- red is best reserved for errors only. If you'd like to fix that I'm happy to merge.

I changed it to yellow instead.

**Review by nponeccop — APPROVED** [review]

**Comment by richbeales** [comment]
Conflicting files
scripts/main.py

**Comment by josephcmiller2** [comment]
De-conflected with latest master.

Currently testing. Will respond shortly.

**Review by nponeccop — DISMISSED** [review]

**Comment by josephcmiller2** [comment]
All test cases PASSED.

**Review by nponeccop — APPROVED** [review]

**Review by richbeales — APPROVED** [review]

**Pull request merged**
