### PR TITLE
Fix command order skip in prompt.txt

### PR DESCRIPTION
**Pull request by AlrikOlson**
Removes skip in #s in the order of the commands in prompt.txt

### Background

Got tired of seeing the # skip in the prompt.txt and always noticed that there were less "failed to parse AI output" and "Invalid JSON" issues after fixing the order

### Changes

Removes the skips in the order of commands in the `prompt.txt` file

### Documentation

prompt.txt is self-documenting

### Test Plan

Ran a few test runs with basic prompts

### PR Quality Checklist
- [x] My pull request is atomic and focuses on a single change.
- [x] I have thoroughly tested my changes with multiple different prompts.
- [x] I have considered potential risks and mitigations for my changes.
- [x] I have documented my changes clearly and comprehensively.
- [x] I have not snuck in any "extra" small tweaks changes

### CODE REVIEW

**Comment by Romelium** [comment]
> This feels like we need benchmarking to prove it out before implementing.

Pretty sure fixing a formatting error does not necessarily require benchmarking.

**Review by Romelium — APPROVED** [review]

**Comment by richbeales** [comment]
You're right, I misread it

**Review by richbeales — APPROVED** [review]

**Comment by AlrikOlson** [comment]
> I wonder if the prompt numbering is intentional, allowing to insert new pieces of prompt in the middle? @Torantulino? If it's a bug, the fix LGTM

Why wouldn't someone just fix the numbering if they want to add/remove a command?

**Comment by nponeccop** [comment]
Because they patch prompts frequently and the renumbering is tedious?

**Comment by AlrikOlson** [comment]
I created a new PR that addresses the fact that renumbering is tedious: #837

**Comment by nponeccop** [comment]
Why is it closed?

**Comment by richbeales** [comment]
closing this in favour of #837

**Pull request closed without merging**
