### PR TITLE
Simple error handling for Open AI Rate limits and Bad Gateway

### PR DESCRIPTION
**Pull request by melambert**
### Background

Additional error handling to retry the chat API in the event of a Bad Gateway 502 or API Rate Limit error 

### Changes

Additional  simple error handling to retry the chat API in the event of a Bad Gateway 502 or API Rate Limit error, with a retry limit of 5 (currently hard coded limit

### Documentation

comment at start of function. Error codes trapped are self explanatory

### Test Plan

I used this in my own local copy of Auto-GPT. Without this change, an API failure would result in the flow going off track, where as by retrying in those situations, Auto-GPT is likely to get the answer the asked.

### PR Quality Checklist
- [x ] My pull request is atomic and focuses on a single change.
- [x] I have thoroughly tested my changes with multiple different prompts.
- [x] I have considered potential risks and mitigations for my changes.
- [x] I have documented my changes clearly and comprehensively.
- [x] I have not snuck in any "extra" small tweaks changes

### CODE REVIEW

**Review by nponeccop — APPROVED** [review]

**Comment by nponeccop** [comment]
@melambert There are conflicts now

**Comment by melambert** [comment]
@nponeccop The conflicts just look to be the replacing of the current functions call with the new functions calls wrapped in the error handling. As such, these are the intended changes. I don't have write access to resolve the conflict. Please advise - apologies but this is my first pull request so I am new to this.

**Comment by nponeccop** [comment]
@p-i- @richbeales can you help?

@melambert You don't need write access to resolve the conflicts in your own PRs, just google or ChatGPT about the procedure

**Comment by melambert** [comment]
@nponeccop Thanks - Ah yes - I see the difference now in the conflict. I missed that before. I'll look into it and see how to resolve.

**Pull request closed without merging**
